# Generated by Django 4.2.7 on 2023-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hottest_article',
            field=models.BooleanField(blank=True, default=False, verbose_name='hottest_article'),
        ),
    ]
