# Generated by Django 4.2.7 on 2023-11-07 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_hottest_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='description_1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description_1'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description_2'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_1'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_2'),
        ),
    ]
