# Generated by Django 4.2.7 on 2023-11-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
