# Generated by Django 4.2.7 on 2023-11-08 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created'),
        ),
    ]
