# Generated by Django 4.2.7 on 2023-11-07 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created'),
        ),
    ]
