# Generated by Django 4.2.7 on 2023-11-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactusmodel_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'ordering': ['datetime_created'], 'verbose_name': 'contact_us_form', 'verbose_name_plural': 'contact_us_form'},
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='topic',
            field=models.CharField(max_length=500, verbose_name='topic'),
        ),
    ]
