# Generated by Django 4.2.7 on 2023-11-07 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_newsemailmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsemailmodel',
            options={'ordering': ['datetime_created'], 'verbose_name': 'news_email_form', 'verbose_name_plural': 'news_email_form'},
        ),
        migrations.AddField(
            model_name='newsemailmodel',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created'),
        ),
    ]
