# Generated by Django 4.2.7 on 2023-11-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='full_name'),
        ),
    ]
